"""
tools/curated_descriptions.py - Hand-curated descriptions for data items whose
upstream source provided none.

These replace the formulaic text produced by tools/backfill_descriptions.py's
synthesiser ("Entity: Title.") with proper editorial descriptions that explain
each field's purpose, units, and the meaning of its allowed values. Keyed by
the item's normalized Name (entity.field). Apply with:

    python3 tools/backfill_descriptions.py --curated

Like the synthesiser, applied text is durable: build_dict.py upserts
Description with COALESCE(excluded, existing) and the seeds carry NULL, so
curated text survives rebuilds and only yields to a real upstream description.

Scope: all 454 items that lacked an upstream description -- the 256
non-Manufacturing items plus the 198 Manufacturing items. Sources: Stripe API,
Microsoft CDM, Odoo, and ERPNext / Frappe Health.
"""

CURATED = {
    # ===================== Customer Relationship Management =====================
    "customer.invoice_settings": "Default invoicing configuration for the customer — custom fields, default payment method, and rendering options applied when generating their invoices.",
    "customer.tax": "Customer-level tax details, including the automatically determined tax location and any recognised tax IDs used for tax calculation.",
    "lead.entity_image_id": "Reference to the image attached to this lead record (entity image), stored as an attachment/file identifier.",

    # ============================ Finance / Accounting ============================
    "charge.billing_details": "Billing name, email, phone, and address captured for this charge, as provided by the customer at payment time.",
    "charge.presentment_details": "Currency and amount as presented to the customer at checkout, when these differ from the settlement currency.",
    "charge.radar_options": "Options for Stripe Radar (fraud detection) applied to this charge, such as a Radar session identifier.",
    "invoice.automatic_tax": "Automatic tax (Stripe Tax) status for the invoice — whether tax was calculated automatically and the outcome of that calculation.",
    "invoice.entity_image_id": "Reference to the image attached to this invoice record (entity image), stored as an attachment/file identifier.",
    "invoice.payment_settings": "Payment configuration for the invoice — accepted payment method types and related options used when collecting payment.",
    "invoice.status_transitions": "Timestamps marking when the invoice moved through key states (finalized, paid, marked uncollectible, voided).",
    "invoice.threshold_reason": "For usage/threshold billing, the reason the invoice was created — the billing thresholds that were reached.",
    "invoiceitem.period": "Service period (start and end) that this invoice line item covers.",
    "invoiceitem.proration_details": "Details of any proration applied to this line item, including the credited amounts it offsets.",
    "payment_intent.amount_details": "Breakdown of the payment amount into components such as tip, where supported.",
    "payment_intent.hooks": "Configuration of programmatic hooks invoked at defined points in the payment intent's processing lifecycle.",
    "payment_intent.payment_details": "Additional structured details about the payment, capturing method-specific or order-level information.",
    "payment_intent.presentment_details": "Currency and amount as presented to the customer, when they differ from the settlement currency.",
    "refund.destination_details": "Method-specific information about where the refund was sent (card, bank transfer, etc.), including network reference data.",
    "refund.next_action": "Any additional action required to complete the refund, such as instructions to display to the customer.",
    "refund.presentment_details": "Currency and amount of the refund as presented to the customer, when different from the settlement currency.",

    # =============================== Human Resources ===============================
    "hr.department.parent_path": "Materialised path of ancestor department IDs, used to model and query the department hierarchy efficiently.",
    "hr.department.plans_count": "Number of planning/allocation plans associated with the department.",
    "hr.employee.certificate": "Highest academic qualification attained by the employee. One of: graduate, bachelor, master, doctor, other.",
    "hr.employee.company_country_code": "ISO country code of the company the employee belongs to, derived from the company's address.",
    "hr.employee.department_id": "Department the employee is assigned to (references hr.department).",
    "hr.employee.gender": "Employee's gender. One of: male, female, other.",
    "hr.employee.job_id": "Job position held by the employee (references hr.job).",
    "hr.employee.message_main_attachment_id": "Primary attachment linked to the employee record, used by Odoo's messaging/attachment system.",
    "hr.employee.resource_calendar_id": "Working-hours schedule (resource calendar) defining the employee's standard working time.",
    "hr.employee.work_permit_scheduled_activity": "Whether a scheduled activity (reminder/task) exists for the employee's work-permit expiry or renewal.",
    "hr.job.active": "Whether the job position is active; inactive positions are archived and hidden from default views.",
    "hr.job.sequence": "Ordering value used to sort job positions in lists.",

    # ============================= Inventory / Warehouse =============================
    "stock.lot.display_complete": "Internal UI flag indicating whether the full lot/serial detail view should be shown.",
    "stock.quant.cyclic_inventory_frequency": "Number of days between scheduled cycle counts for this location/product.",
    "stock.quant.inventory_quantity_set": "Whether a counted inventory quantity has been entered for this quant during a stock count.",
    "stock.quant.priority": "Reservation priority of the quant, influencing the order in which stock is reserved.",
    "stock.quant.product_categ_id": "Product category of the stored product (references product.category).",
    "stock.quant.storage_category_id": "Storage category constraining where this stock may be placed (references stock.storage.category).",
    "stock.quant.tracking": "Tracking method for the product in this quant — none, by lot, or by unique serial number.",

    # =========================== Procurement / Purchasing ===========================
    "purchase_order.date_calendar_start": "Calendar start datetime used to display the purchase order in calendar views.",
    "purchase_order.priority": "Urgency flag for the purchase order. 0 = normal, 1 = urgent.",
    "purchase_order.tax_totals": "Computed summary of tax and total amounts for the order, stored as a structured payload for display.",

    # ============================= Product Master Data =============================
    "product.entity_image_id": "Reference to the image attached to this product record (entity image), stored as an attachment/file identifier.",

    # =========================== Sales / Order Management ===========================
    "order.entity_image_id": "Reference to the image attached to this order record (entity image), stored as an attachment/file identifier.",
    "quote.automatic_tax": "Automatic tax (Stripe Tax) status for the quote — whether tax is calculated automatically.",
    "quote.computed": "Computed totals for the quote (upfront and recurring), derived from its line items.",
    "quote.invoice_settings": "Invoice settings applied to invoices generated when the quote is accepted (e.g. days until due).",
    "quote.status_transitions": "Timestamps marking when the quote was finalized, accepted, or canceled.",
    "quote.subscription_data": "Subscription parameters applied when the accepted quote creates a subscription (trial period, billing cycle anchor, etc.).",
    "quote.total_details": "Breakdown of the quote total, including aggregated discount and tax amounts.",
    "subscription.automatic_tax": "Automatic tax (Stripe Tax) status for the subscription — whether tax is calculated automatically on its invoices.",
    "subscription.billing_mode": "Billing mode controlling how the subscription's charges are calculated and grouped.",
    "subscription.invoice_settings": "Default settings applied to invoices generated for the subscription (default payment method, custom fields, etc.).",
    "subscription.presentment_details": "Currency presented to the customer for the subscription, when it differs from the settlement currency.",

    # ========================== Supply Chain / Logistics ==========================
    "stock.picking.has_tracking": "Whether any product in the transfer is tracked by lot or serial number.",
    "stock.picking.hide_picking_type": "UI flag controlling whether the operation-type field is hidden on the transfer form.",
    "stock.picking.picking_type_code": "Code of the operation type for this transfer — incoming, outgoing, or internal.",
    "stock.picking.picking_type_entire_packs": "Whether the operation type handles entire packages rather than individual products.",
    "stock.picking.products_availability_state": "Overall stock availability for the transfer's products. One of: available, expected, late.",
    "stock.picking.show_clear_qty_button": "UI flag controlling visibility of the 'clear quantities' button on the transfer.",
    "stock.picking.show_lots_text": "UI flag controlling whether lot/serial numbers are shown as free text on the transfer.",
    "stock.picking.show_operations": "UI flag controlling whether the detailed operations (move lines) section is displayed.",
    "stock.picking.show_reserved": "UI flag controlling whether reserved quantities are shown on the transfer.",
    "stock.picking.show_set_qty_button": "UI flag controlling visibility of the 'set quantities' button on the transfer.",
    "stock.picking.type.code": "Direction of operations created under this type. One of: incoming, outgoing, internal.",
    "stock.picking.type.count_picking": "Number of transfers of this operation type (dashboard KPI counter).",
    "stock.picking.type.count_picking_backorders": "Number of back-order transfers of this operation type.",
    "stock.picking.type.count_picking_draft": "Number of draft transfers of this operation type.",
    "stock.picking.type.count_picking_late": "Number of late transfers of this operation type.",
    "stock.picking.type.count_picking_ready": "Number of ready-to-process transfers of this operation type.",
    "stock.picking.type.count_picking_waiting": "Number of waiting transfers of this operation type.",
    "stock.picking.type.hide_reservation_method": "UI flag controlling whether the reservation-method field is hidden for this operation type.",
    "stock.picking.type.package_label_to_print": "Format used when printing package labels for this operation type. One of: pdf, zpl.",
    "stock.picking.type.show_picking_type": "UI flag controlling whether this operation type is shown in the overview.",
    "stock.picking.use_create_lots": "Whether new lot/serial numbers may be created during this transfer.",
    "stock.picking.use_existing_lots": "Whether existing lot/serial numbers may be selected during this transfer.",

    # ================================= Healthcare =================================
    # --- Clinical Procedure ---
    "clinical_procedure.actual_end_datetime": "Date and time the clinical procedure actually ended.",
    "clinical_procedure.actual_start_datetime": "Date and time the clinical procedure actually began.",
    "clinical_procedure.consumable_total_amount": "Total cost of stock items (consumables) used during the procedure.",
    "clinical_procedure.consume_stock": "Whether the procedure consumes stock items from inventory.",
    "clinical_procedure.consumption_details": "Notes describing the consumables used during the procedure.",
    "clinical_procedure.consumption_invoiced": "Whether the consumables used in the procedure have been invoiced.",
    "clinical_procedure.invoice_separately_as_consumables": "Whether consumables are billed to the patient separately from the procedure fee.",
    "clinical_procedure.invoiced": "Whether the procedure itself has been invoiced to the patient.",
    "clinical_procedure.naming_series": "Naming series (prefix) used to generate the procedure's identifier, e.g. HLC-CPR-.YYYY.-",
    "clinical_procedure.notes": "Free-text clinical notes recorded for the procedure.",
    "clinical_procedure.patient_age": "Patient's age at the time of the procedure.",
    "clinical_procedure.patient_name": "Full name of the patient undergoing the procedure.",
    "clinical_procedure.planned_end_datetime": "Scheduled date and time the procedure is expected to end.",
    "clinical_procedure.practitioner_name": "Name of the healthcare practitioner performing the procedure.",
    "clinical_procedure.start_date": "Scheduled date on which the procedure is to start.",
    "clinical_procedure.start_time": "Scheduled time at which the procedure is to start.",
    "clinical_procedure.status": "Workflow state of the procedure. One of: Draft, Submitted, Cancelled, In Progress, Completed, Pending.",
    "clinical_procedure.title": "Display title summarising the procedure (typically patient and procedure type).",
    # --- Lab Test ---
    "lab_test.approved_date": "Date and time the lab test result was approved.",
    "lab_test.custom_result": "Free-form result text used when the test does not fit a structured result format.",
    "lab_test.date": "Date the lab test was created or requested.",
    "lab_test.descriptive_result": "Narrative (descriptive) result of the test, used for non-numeric findings.",
    "lab_test.descriptive_toggle": "Whether the test uses descriptive (narrative) result entry.",
    "lab_test.email": "Email address used to send the lab report to the patient.",
    "lab_test.email_sent": "Whether the lab report has been emailed to the patient.",
    "lab_test.employee_designation": "Job title of the lab technician who performed the test.",
    "lab_test.employee_name": "Name of the lab technician who performed the test.",
    "lab_test.expected_result_date": "Date the test result is expected to be available.",
    "lab_test.expected_result_time": "Time the test result is expected to be available.",
    "lab_test.imaging_toggle": "Whether the test includes imaging-type results.",
    "lab_test.invoiced": "Whether the lab test has been invoiced to the patient.",
    "lab_test.lab_test_comment": "Additional comments recorded for the lab test.",
    "lab_test.lab_test_name": "Name of the lab test performed.",
    "lab_test.legend_print_position": "Where the result legend is printed on the report. One of: Bottom, Top, Both.",
    "lab_test.mobile": "Patient's mobile number used for result notifications.",
    "lab_test.naming_series": "Naming series (prefix) used to generate the lab test's identifier, e.g. HLC-LAB-.YYYY.-",
    "lab_test.normal_toggle": "Whether the test uses the standard numeric result format with normal ranges.",
    "lab_test.patient_age": "Patient's age at the time of the test.",
    "lab_test.patient_name": "Full name of the patient the test was performed for.",
    "lab_test.practitioner_name": "Name of the practitioner who requested the test.",
    "lab_test.printed": "Whether the lab report has been printed.",
    "lab_test.printed_on": "Date and time the lab report was printed.",
    "lab_test.report_preference": "Patient's preferred method of receiving the report (e.g. email or print).",
    "lab_test.result_date": "Date the result was recorded.",
    "lab_test.result_legend": "Explanatory legend printed alongside the test results.",
    "lab_test.sensitivity_toggle": "Whether the test records antibiotic sensitivity (culture) results.",
    "lab_test.sms_sent": "Whether a result notification SMS has been sent to the patient.",
    "lab_test.status": "Workflow state of the lab test. One of: Draft, Completed, Approved, Rejected, Cancelled.",
    "lab_test.submitted_date": "Date and time the lab test was submitted.",
    "lab_test.time": "Time the lab test was created or requested.",
    "lab_test.worksheet_instructions": "Instructions for laboratory staff performing the test.",
    # --- Patient ---
    "patient.alcohol_current_use": "Patient's current alcohol consumption, recorded for clinical history.",
    "patient.alcohol_past_use": "Patient's past alcohol consumption, recorded for clinical history.",
    "patient.allergies": "Known allergies recorded for the patient.",
    "patient.blood_group": "Patient's blood group — one of the eight ABO/Rh types (A/B/AB/O, positive or negative).",
    "patient.dob": "Patient's date of birth.",
    "patient.email": "Patient's email address.",
    "patient.first_name": "Patient's first (given) name.",
    "patient.image": "Profile image of the patient, stored as an attachment reference.",
    "patient.inpatient_status": "Current admission status if the patient is an inpatient. One of: Admission Scheduled, Admitted, Discharge Scheduled.",
    "patient.invite_user": "Whether to create a linked portal user account for the patient.",
    "patient.last_name": "Patient's last (family) name.",
    "patient.medical_history": "Summary of the patient's past medical history.",
    "patient.medication": "Current medications the patient is taking.",
    "patient.middle_name": "Patient's middle name (optional).",
    "patient.mobile": "Patient's mobile phone number.",
    "patient.naming_series": "Naming series (prefix) used to generate the patient's identifier, e.g. HLC-PAT-.YYYY.-",
    "patient.occupation": "Patient's occupation, recorded for clinical and risk assessment.",
    "patient.other_risk_factors": "Other health risk factors noted for the patient.",
    "patient.patient_name": "Patient's full name, composed from the name parts.",
    "patient.phone": "Patient's landline phone number.",
    "patient.report_preference": "Patient's preferred method of receiving reports. One of: Email, Print.",
    "patient.status": "Whether the patient record is Active or Disabled.",
    "patient.surgical_history": "Record of the patient's previous surgeries.",
    "patient.surrounding_factors": "Occupational hazards and environmental factors relevant to the patient's health.",
    "patient.tobacco_current_use": "Patient's current tobacco consumption, recorded for clinical history.",
    "patient.tobacco_past_use": "Patient's past tobacco consumption, recorded for clinical history.",
    "patient.uid": "Patient's unique identification number (e.g. national or hospital ID).",
    "patient.user_id": "Linked system user account for the patient (portal access).",
    # --- Patient Appointment ---
    "patient_appointment.add_video_conferencing": "Whether to attach a video-conferencing link to the appointment.",
    "patient_appointment.appointment_date": "Date of the appointment.",
    "patient_appointment.appointment_datetime": "Combined date and time at which the appointment starts.",
    "patient_appointment.appointment_end_datetime": "Date and time at which the appointment ends.",
    "patient_appointment.appointment_for": "What the appointment is booked against. One of: Practitioner, Department, Service Unit.",
    "patient_appointment.appointment_time": "Time of the appointment.",
    "patient_appointment.coverage_status": "Insurance/coverage status for the appointment.",
    "patient_appointment.duration": "Planned duration of the appointment, in minutes.",
    "patient_appointment.google_meet_link": "Google Meet video-conferencing link for the appointment.",
    "patient_appointment.invoiced": "Whether the appointment has been invoiced.",
    "patient_appointment.naming_series": "Naming series (prefix) used to generate the appointment's identifier, e.g. HLC-APP-.YYYY.-",
    "patient_appointment.notes": "Free-text notes about the appointment.",
    "patient_appointment.paid_amount": "Amount paid by the patient for the appointment.",
    "patient_appointment.patient_age": "Patient's age at the time of the appointment.",
    "patient_appointment.patient_name": "Full name of the patient.",
    "patient_appointment.practitioner_name": "Name of the practitioner the appointment is with.",
    "patient_appointment.reminded": "Whether an appointment reminder has been sent.",
    "patient_appointment.status": "Workflow state of the appointment. One of: Scheduled, Open, Confirmed, Checked In, Checked Out, Closed, Cancelled, No Show.",
    "patient_appointment.title": "Display title summarising the appointment.",
    # --- Patient Encounter ---
    "patient_encounter.coverage_status": "Insurance/coverage status for the encounter.",
    "patient_encounter.diagnosis_in_print": "Whether the diagnosis is included when the encounter is printed.",
    "patient_encounter.encounter_comment": "Reviewing practitioner's notes for the encounter.",
    "patient_encounter.encounter_date": "Date of the clinical encounter.",
    "patient_encounter.encounter_time": "Time of the clinical encounter.",
    "patient_encounter.google_meet_link": "Google Meet video-conferencing link for the encounter.",
    "patient_encounter.inpatient_status": "Inpatient admission status of the patient at the time of the encounter.",
    "patient_encounter.invoiced": "Whether the encounter has been invoiced.",
    "patient_encounter.naming_series": "Naming series (prefix) used to generate the encounter's identifier, e.g. HLC-ENC-.YYYY.-",
    "patient_encounter.patient_age": "Patient's age at the time of the encounter.",
    "patient_encounter.patient_name": "Full name of the patient.",
    "patient_encounter.practitioner_name": "Name of the practitioner conducting the encounter.",
    "patient_encounter.source": "How the patient arrived at the encounter. One of: Direct, Referral, External Referral.",
    "patient_encounter.status": "Workflow state of the encounter. One of: Open, Ordered, Completed, Cancelled.",
    "patient_encounter.submit_orders_on_save": "Whether associated clinical orders are submitted automatically when the encounter is saved.",
    "patient_encounter.symptoms_in_print": "Whether symptoms are included when the encounter is printed.",
    "patient_encounter.title": "Display title summarising the encounter.",
    # --- Vital Signs ---
    "vital_signs.abdomen": "Clinical assessment of the abdomen. One of: Normal, Bloated, Full, Fluid, Constipated.",
    "vital_signs.bmi": "Body mass index, computed from the recorded height and weight.",
    "vital_signs.bp_diastolic": "Diastolic blood pressure reading (mmHg).",
    "vital_signs.bp_systolic": "Systolic blood pressure reading (mmHg).",
    "vital_signs.height": "Patient's height, in metres.",
    "vital_signs.naming_series": "Naming series (prefix) used to generate the vital-signs record's identifier, e.g. HLC-VTS-.YYYY.-",
    "vital_signs.nutrition_note": "Notes on the patient's nutrition.",
    "vital_signs.patient_name": "Full name of the patient.",
    "vital_signs.reflexes": "Clinical assessment of reflexes. One of: Normal, Hyper, Very Hyper, One Sided.",
    "vital_signs.signs_date": "Date the vital signs were recorded.",
    "vital_signs.signs_time": "Time the vital signs were recorded.",
    "vital_signs.title": "Display title summarising the vital-signs record.",
    "vital_signs.tongue": "Clinical assessment of the tongue. One of: Coated, Very Coated, Normal, Furry, Cuts.",
    "vital_signs.vital_signs_note": "General notes recorded with the vital signs.",
    "vital_signs.weight": "Patient's weight, in kilograms.",

    # ============================= Quality Management =============================
    # --- Non Conformance ---
    "non_conformance.corrective_action": "Action taken to correct the identified non-conformance.",
    "non_conformance.details": "Detailed description of the non-conformance.",
    "non_conformance.full_name": "Full name of the person who raised the non-conformance.",
    "non_conformance.preventive_action": "Action taken to prevent recurrence of the non-conformance.",
    "non_conformance.process_owner": "User responsible for the process in which the non-conformance occurred.",
    "non_conformance.status": "Workflow state of the non-conformance. One of: Open, Resolved, Cancelled.",
    "non_conformance.subject": "Short subject line summarising the non-conformance.",
    # --- Quality Action ---
    "quality_action.corrective_preventive": "Whether the action is Corrective (fixes an existing issue) or Preventive (avoids a potential one).",
    "quality_action.date": "Date the quality action was raised.",
    "quality_action.status": "Workflow state of the action. One of: Open, Completed.",
    # --- Quality Goal ---
    "quality_goal.date": "Day of the month on which the goal is reviewed when monitoring monthly.",
    "quality_goal.frequency": "How often the goal is monitored. One of: None, Daily, Weekly, Monthly, Quarterly.",
    "quality_goal.goal": "Statement of the quality goal to be achieved.",
    "quality_goal.weekday": "Day of the week on which the goal is reviewed when monitoring weekly (Monday–Saturday).",
    # --- Quality Inspection ---
    "quality_inspection.child_row_reference": "Internal reference linking the inspection to the source document's item row.",
    "quality_inspection.description": "Description of the item being inspected.",
    "quality_inspection.inspection_type": "Stage at which the inspection occurs. One of: Incoming, Outgoing, In Process.",
    "quality_inspection.item_name": "Name of the item being inspected.",
    "quality_inspection.manual_inspection": "Whether the inspection is performed manually rather than from predefined readings.",
    "quality_inspection.naming_series": "Naming series (prefix) used to generate the inspection's identifier, e.g. MAT-QA-.YYYY.-",
    "quality_inspection.reference_type": "Type of source document the inspection is linked to. One of: Purchase Receipt, Purchase Invoice, Subcontracting Receipt, Delivery Note, Sales Invoice, Stock Entry, Job Card.",
    "quality_inspection.remarks": "Additional remarks recorded for the inspection.",
    "quality_inspection.report_date": "Date the inspection was reported.",
    "quality_inspection.sample_size": "Number of units sampled for the inspection.",
    "quality_inspection.status": "Outcome of the inspection. One of: Accepted, Rejected, Cancelled.",
    "quality_inspection.verified_by": "Name of the person who verified the inspection.",
    # --- Quality Inspection Reading ---
    "quality_inspection_reading.formula_based_criteria": "Whether the acceptance criteria for this reading are evaluated from a formula.",
    "quality_inspection_reading.numeric": "Whether the reading is recorded as a numeric value.",
    "quality_inspection_reading.reading_1": "Recorded value for inspection parameter reading 1.",
    "quality_inspection_reading.reading_2": "Recorded value for inspection parameter reading 2.",
    "quality_inspection_reading.reading_3": "Recorded value for inspection parameter reading 3.",
    "quality_inspection_reading.reading_4": "Recorded value for inspection parameter reading 4.",
    "quality_inspection_reading.reading_5": "Recorded value for inspection parameter reading 5.",
    "quality_inspection_reading.reading_6": "Recorded value for inspection parameter reading 6.",
    "quality_inspection_reading.reading_7": "Recorded value for inspection parameter reading 7.",
    "quality_inspection_reading.reading_8": "Recorded value for inspection parameter reading 8.",
    "quality_inspection_reading.reading_9": "Recorded value for inspection parameter reading 9.",
    "quality_inspection_reading.reading_10": "Recorded value for inspection parameter reading 10.",
    "quality_inspection_reading.reading_value": "Single recorded reading value for the inspected parameter.",
    "quality_inspection_reading.status": "Acceptance result for this reading. One of: Accepted, Rejected.",
    "quality_inspection_reading.value": "Acceptance criteria value the reading is compared against.",
    # --- Quality Procedure ---
    "quality_procedure.is_group": "Whether this procedure is a group node containing child procedures (tree structure).",
    "quality_procedure.lft": "Left index used by the nested-set model to represent the procedure tree.",
    "quality_procedure.old_parent": "Previous parent procedure, retained when the tree is reorganised.",
    "quality_procedure.process_owner_full_name": "Full name of the process owner.",
    "quality_procedure.quality_procedure_name": "Name of the quality procedure.",
    "quality_procedure.rgt": "Right index used by the nested-set model to represent the procedure tree.",
    # --- Quality Review ---
    "quality_review.additional_information": "Additional information recorded for the quality review.",
    "quality_review.date": "Date of the quality review.",
    "quality_review.status": "Outcome of the review. One of: Open, Passed, Failed.",

    # ================================ Manufacturing ================================
    # --- Bill of Materials (ERPNext BOM) ---
    "bom.allow_alternative_item": "Whether items in this BOM may be substituted with their configured alternatives during production.",
    "bom.base_operating_cost": "Operating cost of the BOM, expressed in the company's base currency.",
    "bom.base_raw_material_cost": "Cost of raw materials in the BOM, expressed in the company's base currency.",
    "bom.base_secondary_items_cost": "Cost of secondary (scrap/by-product) items, expressed in the company's base currency.",
    "bom.base_total_cost": "Total cost of the BOM, expressed in the company's base currency.",
    "bom.bom_creator_item": "Link to the BOM Creator item this BOM was generated from.",
    "bom.conversion_rate": "Exchange rate converting the BOM's currency to the company's base currency.",
    "bom.cost_allocation": "Amount of cost allocated to by-products produced alongside the main item.",
    "bom.cost_allocation_per": "Percentage of total cost allocated to by-products.",
    "bom.description": "Description of the item the BOM produces.",
    "bom.fg_based_operating_cost": "Whether operating cost is calculated per finished-good unit rather than from routing operations.",
    "bom.has_variants": "Whether the BOM's item is a template with variants.",
    "bom.image": "Image of the manufactured item.",
    "bom.inspection_required": "Whether a quality inspection is required for the manufactured item.",
    "bom.is_active": "Whether the BOM is active and available for use in production.",
    "bom.is_default": "Whether this is the default BOM for the item when several exist.",
    "bom.is_phantom_bom": "Whether this is a phantom BOM, exploded into its components rather than produced as a stocked item.",
    "bom.item_name": "Name of the item the BOM produces.",
    "bom.operating_cost": "Operating (labour/overhead) cost of the BOM, in its own currency.",
    "bom.operating_cost_per_bom_quantity": "Operating cost per the BOM's stated production quantity.",
    "bom.plc_conversion_rate": "Exchange rate from the price list currency to the company's base currency.",
    "bom.process_loss_percentage": "Expected process loss as a percentage of produced quantity.",
    "bom.process_loss_qty": "Expected quantity lost to process loss during production.",
    "bom.raw_material_cost": "Cost of raw materials in the BOM, in its own currency.",
    "bom.rm_cost_as_per": "Basis used to value raw materials in the BOM. One of: Valuation Rate, Last Purchase Rate, Price List.",
    "bom.route": "URL route (slug) for the BOM's item when published to the website.",
    "bom.secondary_items_cost": "Cost of secondary (scrap/by-product) items, in the BOM's own currency.",
    "bom.set_rate_of_sub_assembly_item_based_on_bom": "Whether sub-assembly item rates are taken from their own BOMs rather than item valuation.",
    "bom.show_in_website": "Whether the BOM's item is published on the website.",
    "bom.show_items": "Whether the items table is shown on the published BOM.",
    "bom.show_operations": "Whether the operations table is shown on the published BOM.",
    "bom.thumbnail": "Thumbnail image of the manufactured item.",
    "bom.total_cost": "Total cost of the BOM in its own currency (raw materials + operating + secondary items).",
    "bom.transfer_material_against": "Whether raw materials are transferred against the Work Order or individual Job Cards. One of: Work Order, Job Card.",
    "bom.web_long_description": "Long item description shown on the website.",
    # --- BOM line item ---
    "bom_item.allow_alternative_item": "Whether this component may be substituted with a configured alternative.",
    "bom_item.amount": "Line amount for the component (rate × quantity), in transaction currency.",
    "bom_item.base_amount": "Line amount for the component, in the company's base currency.",
    "bom_item.base_rate": "Unit rate of the component, in the company's base currency.",
    "bom_item.conversion_factor": "Factor converting the component's stock UOM to the BOM UOM.",
    "bom_item.description": "Description of the component item.",
    "bom_item.do_not_explode": "Whether to keep a sub-assembly component as-is rather than exploding it into its own components.",
    "bom_item.has_variants": "Whether the component item is a template with variants.",
    "bom_item.image": "Image of the component item.",
    "bom_item.include_item_in_manufacturing": "Whether the component is consumed during manufacturing (vs. supplied separately).",
    "bom_item.is_phantom_item": "Whether the component is a phantom item, exploded into its own components.",
    "bom_item.is_stock_item": "Whether the component is a stock-maintained item.",
    "bom_item.is_sub_assembly_item": "Whether the component is itself a manufactured sub-assembly with its own BOM.",
    "bom_item.item_name": "Name of the component item.",
    "bom_item.operation_row_id": "Reference to the routing operation that consumes this component.",
    "bom_item.qty": "Quantity of the component required, in the BOM UOM.",
    "bom_item.qty_consumed_per_unit": "Quantity of the component consumed per unit of finished good.",
    "bom_item.rate": "Unit rate of the component, in transaction currency.",
    "bom_item.sourced_by_supplier": "Whether the component is supplied directly by the subcontractor/supplier rather than issued from stock.",
    "bom_item.stock_qty": "Required quantity expressed in the component's stock UOM.",
    # --- BOM operation ---
    "bom_operation.backflush_from_wip_warehouse": "Whether raw materials for this operation are backflushed (auto-consumed) from the work-in-progress warehouse.",
    "bom_operation.base_cost_per_unit": "Operation cost per finished unit, in the company's base currency.",
    "bom_operation.base_hour_rate": "Hourly rate of the operation's workstation, in the company's base currency.",
    "bom_operation.base_operating_cost": "Operating cost of the operation, in the company's base currency.",
    "bom_operation.batch_size": "Number of units processed per operation batch.",
    "bom_operation.cost_per_unit": "Operation cost per finished unit, in transaction currency.",
    "bom_operation.description": "Description of the operation.",
    "bom_operation.finished_good_qty": "Quantity of finished good produced by this operation.",
    "bom_operation.hour_rate": "Hourly rate of the operation's workstation, in transaction currency.",
    "bom_operation.image": "Image associated with the operation.",
    "bom_operation.is_final_finished_good": "Whether this operation produces the final finished good (vs. an intermediate).",
    "bom_operation.is_subcontracted": "Whether the operation is performed by a subcontractor.",
    "bom_operation.operating_cost": "Operating cost of the operation, in transaction currency.",
    "bom_operation.quality_inspection_required": "Whether a quality inspection is required after the operation.",
    "bom_operation.set_cost_based_on_bom_qty": "Whether operating cost is computed from the BOM's production quantity.",
    "bom_operation.skip_material_transfer": "Whether to skip transferring materials to WIP for this operation.",
    # --- Job Card ---
    "job_card.actual_end_date": "Actual date and time the job finished.",
    "job_card.actual_start_date": "Actual date and time work on the job began.",
    "job_card.backflush_from_wip_warehouse": "Whether materials are backflushed (auto-consumed) from the work-in-progress warehouse.",
    "job_card.expected_end_date": "Planned date and time the job is expected to finish.",
    "job_card.expected_start_date": "Planned date and time the job is expected to start.",
    "job_card.for_quantity": "Quantity to be manufactured under this job card.",
    "job_card.hour_rate": "Hourly rate of the assigned workstation.",
    "job_card.is_corrective_job_card": "Whether this is a corrective job card raised to rework defective output.",
    "job_card.is_paused": "Whether work on the job card is currently paused.",
    "job_card.is_subcontracted": "Whether the job's operation is subcontracted.",
    "job_card.item_name": "Name of the item being manufactured.",
    "job_card.manufactured_qty": "Quantity manufactured so far under this job card.",
    "job_card.naming_series": "Naming series (prefix) used to generate the job card's identifier, e.g. PO-JOB.#####",
    "job_card.operation_id": "Identifier of the operation this job card performs.",
    "job_card.operation_row_id": "Reference to the operation row in the work order.",
    "job_card.operation_row_number": "Row number of the operation within the work order's routing.",
    "job_card.pending_qty": "Quantity still to be manufactured under the job card.",
    "job_card.posting_date": "Accounting posting date of the job card.",
    "job_card.process_loss_qty": "Quantity lost to process loss during the job.",
    "job_card.remarks": "Free-text remarks recorded on the job card.",
    "job_card.requested_qty": "Quantity of raw materials requested for the job.",
    "job_card.sequence_id": "Sequence number determining the order of operations.",
    "job_card.serial_no": "Serial numbers of the items produced or consumed.",
    "job_card.skip_material_transfer": "Whether to skip transferring raw materials to the WIP warehouse for this job.",
    "job_card.status": "Workflow state of the job card. One of: Open, Work In Progress, Partially Transferred, Material Transferred, On Hold, Submitted, Cancelled, Completed.",
    "job_card.time_required": "Expected time required to complete the job, in minutes.",
    "job_card.total_completed_qty": "Total quantity completed across the job card's time logs.",
    "job_card.total_time_in_mins": "Total time logged against the job card, in minutes.",
    "job_card.track_semi_finished_goods": "Whether semi-finished goods are tracked for this job.",
    "job_card.transferred_qty": "Quantity of raw materials transferred to the job.",
    # --- Odoo mrp.bom ---
    "mrp.bom.product_uom_category_id": "Unit-of-measure category of the manufactured product, constraining valid UOMs (references uom.category).",
    "mrp.bom.type": "BOM type. One of: normal (manufactured), phantom (kit, exploded into components).",
    # --- Odoo mrp.bom.byproduct ---
    "mrp.bom.byproduct.company_id": "Company that owns the by-product line (references res.company).",
    "mrp.bom.byproduct.possible_bom_product_template_attribute_value_ids": "Product-variant attribute values for which this by-product line applies.",
    "mrp.bom.byproduct.product_uom_category_id": "Unit-of-measure category of the by-product (references uom.category).",
    # --- Odoo mrp.bom.line ---
    "mrp.bom.line.company_id": "Company that owns the BOM component line (references res.company).",
    "mrp.bom.line.possible_bom_product_template_attribute_value_ids": "Product-variant attribute values for which this component line applies.",
    "mrp.bom.line.product_uom_category_id": "Unit-of-measure category of the component (references uom.category).",
    "mrp.bom.line.tracking": "Tracking method of the component product — none, by lot, or by serial number.",
    # --- Odoo mrp.production (manufacturing order) ---
    "mrp.production.components_availability_state": "Availability of the order's components. One of: available, expected, late, unavailable.",
    "mrp.production.confirm_cancel": "Internal flag prompting confirmation before cancelling the manufacturing order.",
    "mrp.production.consumption": "How strictly component consumption must match the BOM. One of: flexible, warning, strict.",
    "mrp.production.forecasted_issue": "Whether a forecasted shortage is expected for the order's product.",
    "mrp.production.product_tracking": "Tracking method of the manufactured product — none, by lot, or by serial number.",
    "mrp.production.product_uom_category_id": "Unit-of-measure category of the manufactured product (references uom.category).",
    "mrp.production.use_auto_consume_components_lots": "Whether component lots/serials are auto-consumed when producing.",
    "mrp.production.use_create_components_lots": "Whether new lots/serials may be created for components during production.",
    "mrp.production.warehouse_id": "Warehouse in which the manufacturing order is carried out (references stock.warehouse).",
    # --- Odoo mrp.routing.workcenter (routing operation) ---
    "mrp.routing.workcenter.active": "Whether the routing operation is active; inactive operations are archived.",
    "mrp.routing.workcenter.allow_operation_dependencies": "Whether dependencies between operations may be defined for sequencing.",
    "mrp.routing.workcenter.possible_bom_product_template_attribute_value_ids": "Product-variant attribute values for which this operation applies.",
    # --- Odoo mrp.unbuild ---
    "mrp.unbuild.has_tracking": "Tracking method of the product being unbuilt — none, by lot, or by serial number.",
    # --- Odoo mrp.workcenter ---
    "mrp.workcenter.working_state": "Current operating state of the work center. One of: normal, blocked, done.",
    # --- Odoo mrp.workorder ---
    "mrp.workorder.allow_workorder_dependencies": "Whether dependencies between work orders may be defined for sequencing.",
    "mrp.workorder.barcode": "Barcode identifying the work order for shop-floor scanning.",
    "mrp.workorder.company_id": "Company that owns the work order (references res.company).",
    "mrp.workorder.consumption": "How strictly component consumption must match the BOM for this work order.",
    "mrp.workorder.has_worksheet": "Whether the work order has an attached instruction worksheet.",
    "mrp.workorder.is_planned": "Whether the work order has been scheduled/planned.",
    "mrp.workorder.product_id": "Product manufactured by the work order (references product.product).",
    "mrp.workorder.product_tracking": "Tracking method of the manufactured product — none, by lot, or by serial number.",
    # --- Operation (ERPNext) ---
    "operation.batch_size": "Default number of units processed per batch for this operation.",
    "operation.create_job_card_based_on_batch_size": "Whether separate job cards are created per batch when scheduling this operation.",
    "operation.description": "Description of the operation.",
    "operation.is_corrective_operation": "Whether this operation is used to rework/correct defective output.",
    # --- Production Plan ---
    "production_plan.combine_items": "Whether to consolidate identical items across sales orders into a single planned quantity.",
    "production_plan.combine_sub_items": "Whether to consolidate identical sub-assembly items across the plan.",
    "production_plan.consider_minimum_order_qty": "Whether to respect each item's minimum order quantity when planning.",
    "production_plan.from_date": "Start of the date range for selecting source documents.",
    "production_plan.from_delivery_date": "Start of the delivery-date range for selecting demand.",
    "production_plan.get_items_from": "Source of demand for the plan. One of: Sales Order, Material Request.",
    "production_plan.include_non_stock_items": "Whether non-stock items are included in the plan.",
    "production_plan.include_safety_stock": "Whether safety stock is added to the required-quantity calculation.",
    "production_plan.include_subcontracted_items": "Whether subcontracted items are included in the plan.",
    "production_plan.naming_series": "Naming series (prefix) used to generate the plan's identifier, e.g. MFG-PP-.YYYY.-",
    "production_plan.posting_date": "Posting date of the production plan.",
    "production_plan.reserve_stock": "Whether stock is reserved against the plan.",
    "production_plan.sales_order_status": "Filter on sales-order status when pulling demand. One of: To Deliver and Bill, To Bill, To Deliver.",
    "production_plan.status": "Workflow state of the plan. One of: Draft, Submitted, Not Started, In Process, Completed, Closed, Cancelled, Material Requested.",
    "production_plan.to_date": "End of the date range for selecting source documents.",
    "production_plan.to_delivery_date": "End of the delivery-date range for selecting demand.",
    "production_plan.total_planned_qty": "Total quantity planned for production across the plan.",
    "production_plan.total_produced_qty": "Total quantity actually produced against the plan.",
    # --- Routing (ERPNext) ---
    "routing.disabled": "Whether the routing is disabled and unavailable for selection.",
    "routing.routing_name": "Name of the routing (the sequence of operations).",
    # --- Work Order (ERPNext) ---
    "work_order.actual_end_date": "Actual date and time production finished.",
    "work_order.actual_operating_cost": "Actual operating cost incurred, from completed operations.",
    "work_order.actual_start_date": "Actual date and time production began.",
    "work_order.additional_operating_cost": "Additional operating cost added manually to the work order.",
    "work_order.additional_transferred_qty": "Extra raw-material quantity transferred beyond the planned amount.",
    "work_order.allow_alternative_item": "Whether raw materials may be substituted with configured alternatives.",
    "work_order.batch_size": "Number of units per production batch.",
    "work_order.description": "Description of the item being manufactured.",
    "work_order.disassembled_qty": "Quantity disassembled (for unbuild/teardown work orders).",
    "work_order.expected_delivery_date": "Date the finished goods are expected to be delivered.",
    "work_order.from_wip_warehouse": "Whether raw materials are backflushed from the work-in-progress warehouse.",
    "work_order.has_batch_no": "Whether the manufactured item is tracked by batch number.",
    "work_order.has_serial_no": "Whether the manufactured item is tracked by serial number.",
    "work_order.image": "Image of the manufactured item.",
    "work_order.item_name": "Name of the item being manufactured.",
    "work_order.material_request_item": "Link to the originating material-request item, if any.",
    "work_order.material_transferred_for_manufacturing": "Quantity of raw materials transferred to WIP for manufacturing.",
    "work_order.max_producible_qty": "Maximum quantity producible given current material availability.",
    "work_order.naming_series": "Naming series (prefix) used to generate the work order's identifier, e.g. MFG-WO-.YYYY.-",
    "work_order.planned_end_date": "Planned date and time production is expected to finish.",
    "work_order.planned_operating_cost": "Planned operating cost, estimated from the BOM operations.",
    "work_order.planned_start_date": "Planned date and time production is expected to start.",
    "work_order.process_loss_qty": "Quantity expected/recorded as process loss.",
    "work_order.produced_qty": "Quantity manufactured so far.",
    "work_order.production_plan_item": "Link to the production-plan item that generated this work order.",
    "work_order.production_plan_sub_assembly_item": "Link to the production-plan sub-assembly item that generated this work order.",
    "work_order.qty": "Quantity to manufacture.",
    "work_order.reserve_stock": "Whether raw-material stock is reserved for the work order.",
    "work_order.sales_order_item": "Link to the sales-order item this work order fulfils.",
    "work_order.status": "Workflow state of the work order. One of: Draft, Submitted, Not Started, In Process, Stock Reserved, Stock Partially Reserved, Completed, Stopped, Closed, Cancelled.",
    "work_order.subcontracting_inward_order_item": "Link to the related subcontracting order item, if subcontracted.",
    "work_order.total_operating_cost": "Total operating cost of the work order (planned plus additional).",
    "work_order.track_semi_finished_goods": "Whether semi-finished goods are tracked for this work order.",
    "work_order.transfer_material_against": "Whether raw materials are transferred against the Work Order or individual Job Cards. One of: Work Order, Job Card.",
    "work_order.update_consumed_material_cost_in_project": "Whether consumed-material cost is posted to the linked project.",
    # --- Workstation (ERPNext) ---
    "workstation.description": "Description of the workstation.",
    "workstation.disabled": "Whether the workstation is disabled and unavailable for scheduling.",
    "workstation.off_status_image": "Image shown when the workstation is in an inactive state.",
    "workstation.on_status_image": "Image shown when the workstation is in an active state.",
    "workstation.status": "Current state of the workstation. One of: Production, Off, Idle, Problem, Maintenance, Setup.",
    "workstation.total_working_hours": "Total working hours configured for the workstation.",
    "workstation.workstation_name": "Name of the workstation.",
}
