"""
tools/curated_descriptions.py - Hand-curated descriptions for data items whose
upstream source provided none.

These replace the formulaic text produced by tools/backfill_descriptions.py's
synthesiser ("Entity: Title.") with proper editorial descriptions that explain
each field's purpose, units, and the meaning of its allowed values. Keyed by
the item's normalized Name (entity.field). Apply with:

    python3 tools/backfill_descriptions.py --curated

Like the synthesiser, applied text is durable: build_dict.py upserts
Description with COALESCE(excluded, existing) and the seeds carry NULL, so
curated text survives rebuilds and only yields to a real upstream description.

Scope: the 256 non-Manufacturing items that lacked an upstream description
(Manufacturing was curated/handled separately). Sources: Stripe API,
Microsoft CDM, Odoo, and ERPNext / Frappe Health.
"""

CURATED = {
    # ===================== Customer Relationship Management =====================
    "customer.invoice_settings": "Default invoicing configuration for the customer — custom fields, default payment method, and rendering options applied when generating their invoices.",
    "customer.tax": "Customer-level tax details, including the automatically determined tax location and any recognised tax IDs used for tax calculation.",
    "lead.entity_image_id": "Reference to the image attached to this lead record (entity image), stored as an attachment/file identifier.",

    # ============================ Finance / Accounting ============================
    "charge.billing_details": "Billing name, email, phone, and address captured for this charge, as provided by the customer at payment time.",
    "charge.presentment_details": "Currency and amount as presented to the customer at checkout, when these differ from the settlement currency.",
    "charge.radar_options": "Options for Stripe Radar (fraud detection) applied to this charge, such as a Radar session identifier.",
    "invoice.automatic_tax": "Automatic tax (Stripe Tax) status for the invoice — whether tax was calculated automatically and the outcome of that calculation.",
    "invoice.entity_image_id": "Reference to the image attached to this invoice record (entity image), stored as an attachment/file identifier.",
    "invoice.payment_settings": "Payment configuration for the invoice — accepted payment method types and related options used when collecting payment.",
    "invoice.status_transitions": "Timestamps marking when the invoice moved through key states (finalized, paid, marked uncollectible, voided).",
    "invoice.threshold_reason": "For usage/threshold billing, the reason the invoice was created — the billing thresholds that were reached.",
    "invoiceitem.period": "Service period (start and end) that this invoice line item covers.",
    "invoiceitem.proration_details": "Details of any proration applied to this line item, including the credited amounts it offsets.",
    "payment_intent.amount_details": "Breakdown of the payment amount into components such as tip, where supported.",
    "payment_intent.hooks": "Configuration of programmatic hooks invoked at defined points in the payment intent's processing lifecycle.",
    "payment_intent.payment_details": "Additional structured details about the payment, capturing method-specific or order-level information.",
    "payment_intent.presentment_details": "Currency and amount as presented to the customer, when they differ from the settlement currency.",
    "refund.destination_details": "Method-specific information about where the refund was sent (card, bank transfer, etc.), including network reference data.",
    "refund.next_action": "Any additional action required to complete the refund, such as instructions to display to the customer.",
    "refund.presentment_details": "Currency and amount of the refund as presented to the customer, when different from the settlement currency.",

    # =============================== Human Resources ===============================
    "hr.department.parent_path": "Materialised path of ancestor department IDs, used to model and query the department hierarchy efficiently.",
    "hr.department.plans_count": "Number of planning/allocation plans associated with the department.",
    "hr.employee.certificate": "Highest academic qualification attained by the employee. One of: graduate, bachelor, master, doctor, other.",
    "hr.employee.company_country_code": "ISO country code of the company the employee belongs to, derived from the company's address.",
    "hr.employee.department_id": "Department the employee is assigned to (references hr.department).",
    "hr.employee.gender": "Employee's gender. One of: male, female, other.",
    "hr.employee.job_id": "Job position held by the employee (references hr.job).",
    "hr.employee.message_main_attachment_id": "Primary attachment linked to the employee record, used by Odoo's messaging/attachment system.",
    "hr.employee.resource_calendar_id": "Working-hours schedule (resource calendar) defining the employee's standard working time.",
    "hr.employee.work_permit_scheduled_activity": "Whether a scheduled activity (reminder/task) exists for the employee's work-permit expiry or renewal.",
    "hr.job.active": "Whether the job position is active; inactive positions are archived and hidden from default views.",
    "hr.job.sequence": "Ordering value used to sort job positions in lists.",

    # ============================= Inventory / Warehouse =============================
    "stock.lot.display_complete": "Internal UI flag indicating whether the full lot/serial detail view should be shown.",
    "stock.quant.cyclic_inventory_frequency": "Number of days between scheduled cycle counts for this location/product.",
    "stock.quant.inventory_quantity_set": "Whether a counted inventory quantity has been entered for this quant during a stock count.",
    "stock.quant.priority": "Reservation priority of the quant, influencing the order in which stock is reserved.",
    "stock.quant.product_categ_id": "Product category of the stored product (references product.category).",
    "stock.quant.storage_category_id": "Storage category constraining where this stock may be placed (references stock.storage.category).",
    "stock.quant.tracking": "Tracking method for the product in this quant — none, by lot, or by unique serial number.",

    # =========================== Procurement / Purchasing ===========================
    "purchase_order.date_calendar_start": "Calendar start datetime used to display the purchase order in calendar views.",
    "purchase_order.priority": "Urgency flag for the purchase order. 0 = normal, 1 = urgent.",
    "purchase_order.tax_totals": "Computed summary of tax and total amounts for the order, stored as a structured payload for display.",

    # ============================= Product Master Data =============================
    "product.entity_image_id": "Reference to the image attached to this product record (entity image), stored as an attachment/file identifier.",

    # =========================== Sales / Order Management ===========================
    "order.entity_image_id": "Reference to the image attached to this order record (entity image), stored as an attachment/file identifier.",
    "quote.automatic_tax": "Automatic tax (Stripe Tax) status for the quote — whether tax is calculated automatically.",
    "quote.computed": "Computed totals for the quote (upfront and recurring), derived from its line items.",
    "quote.invoice_settings": "Invoice settings applied to invoices generated when the quote is accepted (e.g. days until due).",
    "quote.status_transitions": "Timestamps marking when the quote was finalized, accepted, or canceled.",
    "quote.subscription_data": "Subscription parameters applied when the accepted quote creates a subscription (trial period, billing cycle anchor, etc.).",
    "quote.total_details": "Breakdown of the quote total, including aggregated discount and tax amounts.",
    "subscription.automatic_tax": "Automatic tax (Stripe Tax) status for the subscription — whether tax is calculated automatically on its invoices.",
    "subscription.billing_mode": "Billing mode controlling how the subscription's charges are calculated and grouped.",
    "subscription.invoice_settings": "Default settings applied to invoices generated for the subscription (default payment method, custom fields, etc.).",
    "subscription.presentment_details": "Currency presented to the customer for the subscription, when it differs from the settlement currency.",

    # ========================== Supply Chain / Logistics ==========================
    "stock.picking.has_tracking": "Whether any product in the transfer is tracked by lot or serial number.",
    "stock.picking.hide_picking_type": "UI flag controlling whether the operation-type field is hidden on the transfer form.",
    "stock.picking.picking_type_code": "Code of the operation type for this transfer — incoming, outgoing, or internal.",
    "stock.picking.picking_type_entire_packs": "Whether the operation type handles entire packages rather than individual products.",
    "stock.picking.products_availability_state": "Overall stock availability for the transfer's products. One of: available, expected, late.",
    "stock.picking.show_clear_qty_button": "UI flag controlling visibility of the 'clear quantities' button on the transfer.",
    "stock.picking.show_lots_text": "UI flag controlling whether lot/serial numbers are shown as free text on the transfer.",
    "stock.picking.show_operations": "UI flag controlling whether the detailed operations (move lines) section is displayed.",
    "stock.picking.show_reserved": "UI flag controlling whether reserved quantities are shown on the transfer.",
    "stock.picking.show_set_qty_button": "UI flag controlling visibility of the 'set quantities' button on the transfer.",
    "stock.picking.type.code": "Direction of operations created under this type. One of: incoming, outgoing, internal.",
    "stock.picking.type.count_picking": "Number of transfers of this operation type (dashboard KPI counter).",
    "stock.picking.type.count_picking_backorders": "Number of back-order transfers of this operation type.",
    "stock.picking.type.count_picking_draft": "Number of draft transfers of this operation type.",
    "stock.picking.type.count_picking_late": "Number of late transfers of this operation type.",
    "stock.picking.type.count_picking_ready": "Number of ready-to-process transfers of this operation type.",
    "stock.picking.type.count_picking_waiting": "Number of waiting transfers of this operation type.",
    "stock.picking.type.hide_reservation_method": "UI flag controlling whether the reservation-method field is hidden for this operation type.",
    "stock.picking.type.package_label_to_print": "Format used when printing package labels for this operation type. One of: pdf, zpl.",
    "stock.picking.type.show_picking_type": "UI flag controlling whether this operation type is shown in the overview.",
    "stock.picking.use_create_lots": "Whether new lot/serial numbers may be created during this transfer.",
    "stock.picking.use_existing_lots": "Whether existing lot/serial numbers may be selected during this transfer.",

    # ================================= Healthcare =================================
    # --- Clinical Procedure ---
    "clinical_procedure.actual_end_datetime": "Date and time the clinical procedure actually ended.",
    "clinical_procedure.actual_start_datetime": "Date and time the clinical procedure actually began.",
    "clinical_procedure.consumable_total_amount": "Total cost of stock items (consumables) used during the procedure.",
    "clinical_procedure.consume_stock": "Whether the procedure consumes stock items from inventory.",
    "clinical_procedure.consumption_details": "Notes describing the consumables used during the procedure.",
    "clinical_procedure.consumption_invoiced": "Whether the consumables used in the procedure have been invoiced.",
    "clinical_procedure.invoice_separately_as_consumables": "Whether consumables are billed to the patient separately from the procedure fee.",
    "clinical_procedure.invoiced": "Whether the procedure itself has been invoiced to the patient.",
    "clinical_procedure.naming_series": "Naming series (prefix) used to generate the procedure's identifier, e.g. HLC-CPR-.YYYY.-",
    "clinical_procedure.notes": "Free-text clinical notes recorded for the procedure.",
    "clinical_procedure.patient_age": "Patient's age at the time of the procedure.",
    "clinical_procedure.patient_name": "Full name of the patient undergoing the procedure.",
    "clinical_procedure.planned_end_datetime": "Scheduled date and time the procedure is expected to end.",
    "clinical_procedure.practitioner_name": "Name of the healthcare practitioner performing the procedure.",
    "clinical_procedure.start_date": "Scheduled date on which the procedure is to start.",
    "clinical_procedure.start_time": "Scheduled time at which the procedure is to start.",
    "clinical_procedure.status": "Workflow state of the procedure. One of: Draft, Submitted, Cancelled, In Progress, Completed, Pending.",
    "clinical_procedure.title": "Display title summarising the procedure (typically patient and procedure type).",
    # --- Lab Test ---
    "lab_test.approved_date": "Date and time the lab test result was approved.",
    "lab_test.custom_result": "Free-form result text used when the test does not fit a structured result format.",
    "lab_test.date": "Date the lab test was created or requested.",
    "lab_test.descriptive_result": "Narrative (descriptive) result of the test, used for non-numeric findings.",
    "lab_test.descriptive_toggle": "Whether the test uses descriptive (narrative) result entry.",
    "lab_test.email": "Email address used to send the lab report to the patient.",
    "lab_test.email_sent": "Whether the lab report has been emailed to the patient.",
    "lab_test.employee_designation": "Job title of the lab technician who performed the test.",
    "lab_test.employee_name": "Name of the lab technician who performed the test.",
    "lab_test.expected_result_date": "Date the test result is expected to be available.",
    "lab_test.expected_result_time": "Time the test result is expected to be available.",
    "lab_test.imaging_toggle": "Whether the test includes imaging-type results.",
    "lab_test.invoiced": "Whether the lab test has been invoiced to the patient.",
    "lab_test.lab_test_comment": "Additional comments recorded for the lab test.",
    "lab_test.lab_test_name": "Name of the lab test performed.",
    "lab_test.legend_print_position": "Where the result legend is printed on the report. One of: Bottom, Top, Both.",
    "lab_test.mobile": "Patient's mobile number used for result notifications.",
    "lab_test.naming_series": "Naming series (prefix) used to generate the lab test's identifier, e.g. HLC-LAB-.YYYY.-",
    "lab_test.normal_toggle": "Whether the test uses the standard numeric result format with normal ranges.",
    "lab_test.patient_age": "Patient's age at the time of the test.",
    "lab_test.patient_name": "Full name of the patient the test was performed for.",
    "lab_test.practitioner_name": "Name of the practitioner who requested the test.",
    "lab_test.printed": "Whether the lab report has been printed.",
    "lab_test.printed_on": "Date and time the lab report was printed.",
    "lab_test.report_preference": "Patient's preferred method of receiving the report (e.g. email or print).",
    "lab_test.result_date": "Date the result was recorded.",
    "lab_test.result_legend": "Explanatory legend printed alongside the test results.",
    "lab_test.sensitivity_toggle": "Whether the test records antibiotic sensitivity (culture) results.",
    "lab_test.sms_sent": "Whether a result notification SMS has been sent to the patient.",
    "lab_test.status": "Workflow state of the lab test. One of: Draft, Completed, Approved, Rejected, Cancelled.",
    "lab_test.submitted_date": "Date and time the lab test was submitted.",
    "lab_test.time": "Time the lab test was created or requested.",
    "lab_test.worksheet_instructions": "Instructions for laboratory staff performing the test.",
    # --- Patient ---
    "patient.alcohol_current_use": "Patient's current alcohol consumption, recorded for clinical history.",
    "patient.alcohol_past_use": "Patient's past alcohol consumption, recorded for clinical history.",
    "patient.allergies": "Known allergies recorded for the patient.",
    "patient.blood_group": "Patient's blood group — one of the eight ABO/Rh types (A/B/AB/O, positive or negative).",
    "patient.dob": "Patient's date of birth.",
    "patient.email": "Patient's email address.",
    "patient.first_name": "Patient's first (given) name.",
    "patient.image": "Profile image of the patient, stored as an attachment reference.",
    "patient.inpatient_status": "Current admission status if the patient is an inpatient. One of: Admission Scheduled, Admitted, Discharge Scheduled.",
    "patient.invite_user": "Whether to create a linked portal user account for the patient.",
    "patient.last_name": "Patient's last (family) name.",
    "patient.medical_history": "Summary of the patient's past medical history.",
    "patient.medication": "Current medications the patient is taking.",
    "patient.middle_name": "Patient's middle name (optional).",
    "patient.mobile": "Patient's mobile phone number.",
    "patient.naming_series": "Naming series (prefix) used to generate the patient's identifier, e.g. HLC-PAT-.YYYY.-",
    "patient.occupation": "Patient's occupation, recorded for clinical and risk assessment.",
    "patient.other_risk_factors": "Other health risk factors noted for the patient.",
    "patient.patient_name": "Patient's full name, composed from the name parts.",
    "patient.phone": "Patient's landline phone number.",
    "patient.report_preference": "Patient's preferred method of receiving reports. One of: Email, Print.",
    "patient.status": "Whether the patient record is Active or Disabled.",
    "patient.surgical_history": "Record of the patient's previous surgeries.",
    "patient.surrounding_factors": "Occupational hazards and environmental factors relevant to the patient's health.",
    "patient.tobacco_current_use": "Patient's current tobacco consumption, recorded for clinical history.",
    "patient.tobacco_past_use": "Patient's past tobacco consumption, recorded for clinical history.",
    "patient.uid": "Patient's unique identification number (e.g. national or hospital ID).",
    "patient.user_id": "Linked system user account for the patient (portal access).",
    # --- Patient Appointment ---
    "patient_appointment.add_video_conferencing": "Whether to attach a video-conferencing link to the appointment.",
    "patient_appointment.appointment_date": "Date of the appointment.",
    "patient_appointment.appointment_datetime": "Combined date and time at which the appointment starts.",
    "patient_appointment.appointment_end_datetime": "Date and time at which the appointment ends.",
    "patient_appointment.appointment_for": "What the appointment is booked against. One of: Practitioner, Department, Service Unit.",
    "patient_appointment.appointment_time": "Time of the appointment.",
    "patient_appointment.coverage_status": "Insurance/coverage status for the appointment.",
    "patient_appointment.duration": "Planned duration of the appointment, in minutes.",
    "patient_appointment.google_meet_link": "Google Meet video-conferencing link for the appointment.",
    "patient_appointment.invoiced": "Whether the appointment has been invoiced.",
    "patient_appointment.naming_series": "Naming series (prefix) used to generate the appointment's identifier, e.g. HLC-APP-.YYYY.-",
    "patient_appointment.notes": "Free-text notes about the appointment.",
    "patient_appointment.paid_amount": "Amount paid by the patient for the appointment.",
    "patient_appointment.patient_age": "Patient's age at the time of the appointment.",
    "patient_appointment.patient_name": "Full name of the patient.",
    "patient_appointment.practitioner_name": "Name of the practitioner the appointment is with.",
    "patient_appointment.reminded": "Whether an appointment reminder has been sent.",
    "patient_appointment.status": "Workflow state of the appointment. One of: Scheduled, Open, Confirmed, Checked In, Checked Out, Closed, Cancelled, No Show.",
    "patient_appointment.title": "Display title summarising the appointment.",
    # --- Patient Encounter ---
    "patient_encounter.coverage_status": "Insurance/coverage status for the encounter.",
    "patient_encounter.diagnosis_in_print": "Whether the diagnosis is included when the encounter is printed.",
    "patient_encounter.encounter_comment": "Reviewing practitioner's notes for the encounter.",
    "patient_encounter.encounter_date": "Date of the clinical encounter.",
    "patient_encounter.encounter_time": "Time of the clinical encounter.",
    "patient_encounter.google_meet_link": "Google Meet video-conferencing link for the encounter.",
    "patient_encounter.inpatient_status": "Inpatient admission status of the patient at the time of the encounter.",
    "patient_encounter.invoiced": "Whether the encounter has been invoiced.",
    "patient_encounter.naming_series": "Naming series (prefix) used to generate the encounter's identifier, e.g. HLC-ENC-.YYYY.-",
    "patient_encounter.patient_age": "Patient's age at the time of the encounter.",
    "patient_encounter.patient_name": "Full name of the patient.",
    "patient_encounter.practitioner_name": "Name of the practitioner conducting the encounter.",
    "patient_encounter.source": "How the patient arrived at the encounter. One of: Direct, Referral, External Referral.",
    "patient_encounter.status": "Workflow state of the encounter. One of: Open, Ordered, Completed, Cancelled.",
    "patient_encounter.submit_orders_on_save": "Whether associated clinical orders are submitted automatically when the encounter is saved.",
    "patient_encounter.symptoms_in_print": "Whether symptoms are included when the encounter is printed.",
    "patient_encounter.title": "Display title summarising the encounter.",
    # --- Vital Signs ---
    "vital_signs.abdomen": "Clinical assessment of the abdomen. One of: Normal, Bloated, Full, Fluid, Constipated.",
    "vital_signs.bmi": "Body mass index, computed from the recorded height and weight.",
    "vital_signs.bp_diastolic": "Diastolic blood pressure reading (mmHg).",
    "vital_signs.bp_systolic": "Systolic blood pressure reading (mmHg).",
    "vital_signs.height": "Patient's height, in metres.",
    "vital_signs.naming_series": "Naming series (prefix) used to generate the vital-signs record's identifier, e.g. HLC-VTS-.YYYY.-",
    "vital_signs.nutrition_note": "Notes on the patient's nutrition.",
    "vital_signs.patient_name": "Full name of the patient.",
    "vital_signs.reflexes": "Clinical assessment of reflexes. One of: Normal, Hyper, Very Hyper, One Sided.",
    "vital_signs.signs_date": "Date the vital signs were recorded.",
    "vital_signs.signs_time": "Time the vital signs were recorded.",
    "vital_signs.title": "Display title summarising the vital-signs record.",
    "vital_signs.tongue": "Clinical assessment of the tongue. One of: Coated, Very Coated, Normal, Furry, Cuts.",
    "vital_signs.vital_signs_note": "General notes recorded with the vital signs.",
    "vital_signs.weight": "Patient's weight, in kilograms.",

    # ============================= Quality Management =============================
    # --- Non Conformance ---
    "non_conformance.corrective_action": "Action taken to correct the identified non-conformance.",
    "non_conformance.details": "Detailed description of the non-conformance.",
    "non_conformance.full_name": "Full name of the person who raised the non-conformance.",
    "non_conformance.preventive_action": "Action taken to prevent recurrence of the non-conformance.",
    "non_conformance.process_owner": "User responsible for the process in which the non-conformance occurred.",
    "non_conformance.status": "Workflow state of the non-conformance. One of: Open, Resolved, Cancelled.",
    "non_conformance.subject": "Short subject line summarising the non-conformance.",
    # --- Quality Action ---
    "quality_action.corrective_preventive": "Whether the action is Corrective (fixes an existing issue) or Preventive (avoids a potential one).",
    "quality_action.date": "Date the quality action was raised.",
    "quality_action.status": "Workflow state of the action. One of: Open, Completed.",
    # --- Quality Goal ---
    "quality_goal.date": "Day of the month on which the goal is reviewed when monitoring monthly.",
    "quality_goal.frequency": "How often the goal is monitored. One of: None, Daily, Weekly, Monthly, Quarterly.",
    "quality_goal.goal": "Statement of the quality goal to be achieved.",
    "quality_goal.weekday": "Day of the week on which the goal is reviewed when monitoring weekly (Monday–Saturday).",
    # --- Quality Inspection ---
    "quality_inspection.child_row_reference": "Internal reference linking the inspection to the source document's item row.",
    "quality_inspection.description": "Description of the item being inspected.",
    "quality_inspection.inspection_type": "Stage at which the inspection occurs. One of: Incoming, Outgoing, In Process.",
    "quality_inspection.item_name": "Name of the item being inspected.",
    "quality_inspection.manual_inspection": "Whether the inspection is performed manually rather than from predefined readings.",
    "quality_inspection.naming_series": "Naming series (prefix) used to generate the inspection's identifier, e.g. MAT-QA-.YYYY.-",
    "quality_inspection.reference_type": "Type of source document the inspection is linked to. One of: Purchase Receipt, Purchase Invoice, Subcontracting Receipt, Delivery Note, Sales Invoice, Stock Entry, Job Card.",
    "quality_inspection.remarks": "Additional remarks recorded for the inspection.",
    "quality_inspection.report_date": "Date the inspection was reported.",
    "quality_inspection.sample_size": "Number of units sampled for the inspection.",
    "quality_inspection.status": "Outcome of the inspection. One of: Accepted, Rejected, Cancelled.",
    "quality_inspection.verified_by": "Name of the person who verified the inspection.",
    # --- Quality Inspection Reading ---
    "quality_inspection_reading.formula_based_criteria": "Whether the acceptance criteria for this reading are evaluated from a formula.",
    "quality_inspection_reading.numeric": "Whether the reading is recorded as a numeric value.",
    "quality_inspection_reading.reading_1": "Recorded value for inspection parameter reading 1.",
    "quality_inspection_reading.reading_2": "Recorded value for inspection parameter reading 2.",
    "quality_inspection_reading.reading_3": "Recorded value for inspection parameter reading 3.",
    "quality_inspection_reading.reading_4": "Recorded value for inspection parameter reading 4.",
    "quality_inspection_reading.reading_5": "Recorded value for inspection parameter reading 5.",
    "quality_inspection_reading.reading_6": "Recorded value for inspection parameter reading 6.",
    "quality_inspection_reading.reading_7": "Recorded value for inspection parameter reading 7.",
    "quality_inspection_reading.reading_8": "Recorded value for inspection parameter reading 8.",
    "quality_inspection_reading.reading_9": "Recorded value for inspection parameter reading 9.",
    "quality_inspection_reading.reading_10": "Recorded value for inspection parameter reading 10.",
    "quality_inspection_reading.reading_value": "Single recorded reading value for the inspected parameter.",
    "quality_inspection_reading.status": "Acceptance result for this reading. One of: Accepted, Rejected.",
    "quality_inspection_reading.value": "Acceptance criteria value the reading is compared against.",
    # --- Quality Procedure ---
    "quality_procedure.is_group": "Whether this procedure is a group node containing child procedures (tree structure).",
    "quality_procedure.lft": "Left index used by the nested-set model to represent the procedure tree.",
    "quality_procedure.old_parent": "Previous parent procedure, retained when the tree is reorganised.",
    "quality_procedure.process_owner_full_name": "Full name of the process owner.",
    "quality_procedure.quality_procedure_name": "Name of the quality procedure.",
    "quality_procedure.rgt": "Right index used by the nested-set model to represent the procedure tree.",
    # --- Quality Review ---
    "quality_review.additional_information": "Additional information recorded for the quality review.",
    "quality_review.date": "Date of the quality review.",
    "quality_review.status": "Outcome of the review. One of: Open, Passed, Failed.",
}
